cache ToolchainCluster CR only in the given namespace
codeready-toolchain/host-operator pull request #1067
Opened 2024-07-26 07:23 UTC by fbm3307

This is related to https://github.com/codeready-toolchain/toolchain-common/pull/419

This is just a dependency check

2024-08-01 14:01 UTC, rajivnathan approved these changes

2024-08-01 16:49 UTC, alexeykazakov requested changes

2024-08-01 16:49 UTC, alexeykazakov commented on go.sum
> +github.com/MatousJobanek/toolchain-common v0.0.0-20240726063305-474ff3c9f3fd/go.mod h1:LGk4lAYtvYPXgopPW65aoa7c5KiKq6Ssuytgckc31Wk=
Please do `go mod tidy`

2024-08-02 05:57 UTC, fbm3307 commented on go.sum
> +github.com/MatousJobanek/toolchain-common v0.0.0-20240726063305-474ff3c9f3fd/go.mod h1:LGk4lAYtvYPXgopPW65aoa7c5KiKq6Ssuytgckc31Wk=
done

2024-08-02 16:31 UTC, alexeykazakov approved these changes

2024-08-05 09:57 UTC, closed without merging

2024-08-05 09:57 UTC, MatousJobanek commented
It looks like that there is no change in this PR anymore as the toolchain-common dependency was updated via another PR that is already merged. 
Closing it...