comment out unneeded logs
codeready-toolchain/host-operator pull request #724
Opened 2023-01-10 14:17 UTC by xcoulon

Signed-off-by: Xavier Coulon <xcoulon@redhat.com>

2023-01-11 08:10 UTC, mfrancisc commented
Even here it would be nice if the logging library could provide a debug level (`logger.Debug(string)`) so that we can keep those logs turned on only when the operator is deployed in debugging mode for examlpe.

2023-01-11 10:03 UTC, MatousJobanek requested changes
TBH, I would love to keep these logs there because they are super helpful when analyzing logs for some troubleshooting.

2023-01-11 13:59 UTC, xcoulon commented
> TBH, I would love to keep these logs there because they are super helpful when analyzing logs for some troubleshooting.

all of them?

2023-01-16 08:59 UTC, mfrancisc commented on go.mod
> +replace github.com/codeready-toolchain/toolchain-common => github.com/xcoulon/toolchain-common v0.0.0-20230111085908-1dc1cb70f1e9
friendly reminder

2023-01-16 09:00 UTC, mfrancisc approved these changes

2023-01-16 09:00 UTC, MatousJobanek approved these changes
Approving since it doesn't remove any logs now.
Thanks for changing it

2023-01-16 10:41 UTC, merged