Add a dedicated service account to run Tekton pipelines
codeready-toolchain/host-operator pull request #797
Opened 2023-05-01 12:43 UTC by Roming22

The service account is to be created automatically on tenant namespace creation

2023-05-01 19:06 UTC, Roming22 commented
@alexeykazakov PR opened: https://github.com/codeready-toolchain/toolchain-e2e/pull/718

2023-05-01 20:07 UTC, alexeykazakov commented
/ok-to-test

2023-05-01 21:35 UTC, alexeykazakov commented on deploy/templates/nstemplatetiers/appstudio/ns_tenant.yaml
> +      apiGroup: rbac.authorization.k8s.io
```suggestion
      namespace: ${USERNAME}-tenant
```

2023-05-01 22:34 UTC, alexeykazakov requested changes
The PR looks good. I'm blocking it just to make sure the PR doesn't get merged until we update the member operator permissions.

2023-05-08 15:55 UTC, MatousJobanek commented on deploy/templates/nstemplatetiers/appstudio/ns_tenant.yaml
> +    name: appstudio-pipelines-runner-clusterrole
https://github.com/codeready-toolchain/member-operator/blob/abc7052dba35ef660902664fd843c38a6ec37882/config/appstudio-pipelines-runner/base/appstudio_pipelines_runner_role.yaml#L2-L5
```suggestion
    name: appstudio-pipelines-runner
```

2023-05-08 16:44 UTC, MatousJobanek commented
@alexeykazakov for this PR I only updated the name of ClusterRole in the ClusterRoleBinding so it matches what is in the manifests in member-operator 
https://github.com/codeready-toolchain/member-operator/blob/abc7052dba35ef660902664fd843c38a6ec37882/config/appstudio-pipelines-runner/base/appstudio_pipelines_runner_role.yaml#L2-L5
commit: https://github.com/codeready-toolchain/host-operator/pull/797/commits/ed5fce436e0e9029bcc3ed513d83692e38ca98c4

2023-05-08 17:12 UTC, MatousJobanek approved these changes

2023-05-08 17:16 UTC, alexeykazakov approved these changes

2023-05-08 18:33 UTC, ranakan19 commented
/retest

2023-05-08 18:50 UTC, rajivnathan approved these changes

2023-05-08 20:06 UTC, rajivnathan commented
/retest

2023-05-08 22:47 UTC, merged